// js/csf-catalog.js — NIST CSF 2.0 Core catalog (generated by scripts/build-csf-catalog.mjs)
// Source: NIST.CSWP.29 Appendix A. Do not edit by hand — regenerate via npm run build:csf-catalog

const FUNCTIONS = {
  "GV": "Govern",
  "ID": "Identify",
  "PR": "Protect",
  "DE": "Detect",
  "RS": "Respond",
  "RC": "Recover"
};

const CATEGORIES = [
  {
    "id": "GV.OC",
    "fn": "GV",
    "name": "Organizational Context",
    "subCount": 5
  },
  {
    "id": "GV.RM",
    "fn": "GV",
    "name": "Risk Management Strategy",
    "subCount": 7
  },
  {
    "id": "GV.RR",
    "fn": "GV",
    "name": "Roles, Responsibilities, and Authorities",
    "subCount": 4
  },
  {
    "id": "GV.PO",
    "fn": "GV",
    "name": "Policy",
    "subCount": 2
  },
  {
    "id": "GV.OV",
    "fn": "GV",
    "name": "Oversight",
    "subCount": 3
  },
  {
    "id": "GV.SC",
    "fn": "GV",
    "name": "Cybersecurity Supply Chain Risk Management",
    "subCount": 10
  },
  {
    "id": "ID.AM",
    "fn": "ID",
    "name": "Asset Management",
    "subCount": 7
  },
  {
    "id": "ID.RA",
    "fn": "ID",
    "name": "Risk Assessment",
    "subCount": 10
  },
  {
    "id": "ID.IM",
    "fn": "ID",
    "name": "Improvement",
    "subCount": 4
  },
  {
    "id": "PR.AA",
    "fn": "PR",
    "name": "Identity Management, Authentication, and Access Control",
    "subCount": 6
  },
  {
    "id": "PR.AT",
    "fn": "PR",
    "name": "Awareness and Training",
    "subCount": 2
  },
  {
    "id": "PR.DS",
    "fn": "PR",
    "name": "Data Security",
    "subCount": 4
  },
  {
    "id": "PR.PS",
    "fn": "PR",
    "name": "Platform Security",
    "subCount": 6
  },
  {
    "id": "PR.IR",
    "fn": "PR",
    "name": "Technology Infrastructure Resilience",
    "subCount": 4
  },
  {
    "id": "DE.CM",
    "fn": "DE",
    "name": "Continuous Monitoring",
    "subCount": 5
  },
  {
    "id": "DE.AE",
    "fn": "DE",
    "name": "Adverse Event Analysis",
    "subCount": 6
  },
  {
    "id": "RS.MA",
    "fn": "RS",
    "name": "Incident Management",
    "subCount": 5
  },
  {
    "id": "RS.AN",
    "fn": "RS",
    "name": "Incident Analysis",
    "subCount": 4
  },
  {
    "id": "RS.CO",
    "fn": "RS",
    "name": "Incident Response Reporting and Communication",
    "subCount": 2
  },
  {
    "id": "RS.MI",
    "fn": "RS",
    "name": "Incident Mitigation",
    "subCount": 2
  },
  {
    "id": "RC.RP",
    "fn": "RC",
    "name": "Incident Recovery Plan Execution",
    "subCount": 6
  },
  {
    "id": "RC.CO",
    "fn": "RC",
    "name": "Incident Recovery Communication",
    "subCount": 2
  }
];

const SUBCATEGORIES = [
  {
    "id": "GV.OC-01",
    "cat": "GV.OC",
    "fn": "GV",
    "n": "Mission informs risk management"
  },
  {
    "id": "GV.OC-02",
    "cat": "GV.OC",
    "fn": "GV",
    "n": "Stakeholder expectations"
  },
  {
    "id": "GV.OC-03",
    "cat": "GV.OC",
    "fn": "GV",
    "n": "Legal and regulatory requirements"
  },
  {
    "id": "GV.OC-04",
    "cat": "GV.OC",
    "fn": "GV",
    "n": "Critical dependencies communicated"
  },
  {
    "id": "GV.OC-05",
    "cat": "GV.OC",
    "fn": "GV",
    "n": "Organizational dependencies understood"
  },
  {
    "id": "GV.RM-01",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Risk management objectives"
  },
  {
    "id": "GV.RM-02",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Risk appetite and tolerance"
  },
  {
    "id": "GV.RM-03",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Enterprise risk integration"
  },
  {
    "id": "GV.RM-04",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Risk response options"
  },
  {
    "id": "GV.RM-05",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Risk communication lines"
  },
  {
    "id": "GV.RM-06",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Standardized risk method"
  },
  {
    "id": "GV.RM-07",
    "cat": "GV.RM",
    "fn": "GV",
    "n": "Positive risks characterized"
  },
  {
    "id": "GV.RR-01",
    "cat": "GV.RR",
    "fn": "GV",
    "n": "Leadership accountability"
  },
  {
    "id": "GV.RR-02",
    "cat": "GV.RR",
    "fn": "GV",
    "n": "Roles and authorities established"
  },
  {
    "id": "GV.RR-03",
    "cat": "GV.RR",
    "fn": "GV",
    "n": "Adequate resources"
  },
  {
    "id": "GV.RR-04",
    "cat": "GV.RR",
    "fn": "GV",
    "n": "Cybersecurity in HR practices"
  },
  {
    "id": "GV.PO-01",
    "cat": "GV.PO",
    "fn": "GV",
    "n": "Cybersecurity policy established"
  },
  {
    "id": "GV.PO-02",
    "cat": "GV.PO",
    "fn": "GV",
    "n": "Policy reviewed and updated"
  },
  {
    "id": "GV.OV-01",
    "cat": "GV.OV",
    "fn": "GV",
    "n": "Strategy outcomes reviewed"
  },
  {
    "id": "GV.OV-02",
    "cat": "GV.OV",
    "fn": "GV",
    "n": "Strategy coverage reviewed"
  },
  {
    "id": "GV.OV-03",
    "cat": "GV.OV",
    "fn": "GV",
    "n": "Performance evaluated"
  },
  {
    "id": "GV.SC-01",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Supply chain program established"
  },
  {
    "id": "GV.SC-02",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Supplier roles coordinated"
  },
  {
    "id": "GV.SC-03",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Supply chain risk integrated"
  },
  {
    "id": "GV.SC-04",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Suppliers prioritized"
  },
  {
    "id": "GV.SC-05",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Supply chain requirements in contracts"
  },
  {
    "id": "GV.SC-06",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Due diligence before relationships"
  },
  {
    "id": "GV.SC-07",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Supplier risks managed"
  },
  {
    "id": "GV.SC-08",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Suppliers in incident planning"
  },
  {
    "id": "GV.SC-09",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Supply chain practices monitored"
  },
  {
    "id": "GV.SC-10",
    "cat": "GV.SC",
    "fn": "GV",
    "n": "Post-agreement provisions"
  },
  {
    "id": "ID.AM-01",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Hardware inventories"
  },
  {
    "id": "ID.AM-02",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Software inventories"
  },
  {
    "id": "ID.AM-03",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Network data flows"
  },
  {
    "id": "ID.AM-04",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Supplier service inventories"
  },
  {
    "id": "ID.AM-05",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Asset prioritization"
  },
  {
    "id": "ID.AM-07",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Data inventories"
  },
  {
    "id": "ID.AM-08",
    "cat": "ID.AM",
    "fn": "ID",
    "n": "Asset life cycles"
  },
  {
    "id": "ID.RA-01",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Vulnerabilities identified"
  },
  {
    "id": "ID.RA-02",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Threat intelligence received"
  },
  {
    "id": "ID.RA-03",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Threats identified"
  },
  {
    "id": "ID.RA-04",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Impacts and likelihoods"
  },
  {
    "id": "ID.RA-05",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Inherent risk understood"
  },
  {
    "id": "ID.RA-06",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Risk responses planned"
  },
  {
    "id": "ID.RA-07",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Changes and exceptions managed"
  },
  {
    "id": "ID.RA-08",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Vulnerability disclosure processes"
  },
  {
    "id": "ID.RA-09",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Hardware and software integrity"
  },
  {
    "id": "ID.RA-10",
    "cat": "ID.RA",
    "fn": "ID",
    "n": "Critical supplier assessment"
  },
  {
    "id": "ID.IM-01",
    "cat": "ID.IM",
    "fn": "ID",
    "n": "Improvements from evaluations"
  },
  {
    "id": "ID.IM-02",
    "cat": "ID.IM",
    "fn": "ID",
    "n": "Improvements from tests"
  },
  {
    "id": "ID.IM-03",
    "cat": "ID.IM",
    "fn": "ID",
    "n": "Improvements from operations"
  },
  {
    "id": "ID.IM-04",
    "cat": "ID.IM",
    "fn": "ID",
    "n": "Plans maintained and improved"
  },
  {
    "id": "PR.AA-01",
    "cat": "PR.AA",
    "fn": "PR",
    "n": "Identities managed"
  },
  {
    "id": "PR.AA-02",
    "cat": "PR.AA",
    "fn": "PR",
    "n": "Identities proofed"
  },
  {
    "id": "PR.AA-03",
    "cat": "PR.AA",
    "fn": "PR",
    "n": "Authentication"
  },
  {
    "id": "PR.AA-04",
    "cat": "PR.AA",
    "fn": "PR",
    "n": "Identity assertions protected"
  },
  {
    "id": "PR.AA-05",
    "cat": "PR.AA",
    "fn": "PR",
    "n": "Access permissions managed"
  },
  {
    "id": "PR.AA-06",
    "cat": "PR.AA",
    "fn": "PR",
    "n": "Physical access managed"
  },
  {
    "id": "PR.AT-01",
    "cat": "PR.AT",
    "fn": "PR",
    "n": "General awareness and training"
  },
  {
    "id": "PR.AT-02",
    "cat": "PR.AT",
    "fn": "PR",
    "n": "Specialized role training"
  },
  {
    "id": "PR.DS-01",
    "cat": "PR.DS",
    "fn": "PR",
    "n": "Data-at-rest protected"
  },
  {
    "id": "PR.DS-02",
    "cat": "PR.DS",
    "fn": "PR",
    "n": "Data-in-transit protected"
  },
  {
    "id": "PR.DS-10",
    "cat": "PR.DS",
    "fn": "PR",
    "n": "Data-in-use protected"
  },
  {
    "id": "PR.DS-11",
    "cat": "PR.DS",
    "fn": "PR",
    "n": "Backups protected and tested"
  },
  {
    "id": "PR.PS-01",
    "cat": "PR.PS",
    "fn": "PR",
    "n": "Configuration management"
  },
  {
    "id": "PR.PS-02",
    "cat": "PR.PS",
    "fn": "PR",
    "n": "Software maintained"
  },
  {
    "id": "PR.PS-03",
    "cat": "PR.PS",
    "fn": "PR",
    "n": "Hardware maintained"
  },
  {
    "id": "PR.PS-04",
    "cat": "PR.PS",
    "fn": "PR",
    "n": "Logs for monitoring"
  },
  {
    "id": "PR.PS-05",
    "cat": "PR.PS",
    "fn": "PR",
    "n": "Unauthorized software prevented"
  },
  {
    "id": "PR.PS-06",
    "cat": "PR.PS",
    "fn": "PR",
    "n": "Secure software development"
  },
  {
    "id": "PR.IR-01",
    "cat": "PR.IR",
    "fn": "PR",
    "n": "Networks protected"
  },
  {
    "id": "PR.IR-02",
    "cat": "PR.IR",
    "fn": "PR",
    "n": "Environmental threats"
  },
  {
    "id": "PR.IR-03",
    "cat": "PR.IR",
    "fn": "PR",
    "n": "Resilience mechanisms"
  },
  {
    "id": "PR.IR-04",
    "cat": "PR.IR",
    "fn": "PR",
    "n": "Resource capacity"
  },
  {
    "id": "DE.CM-01",
    "cat": "DE.CM",
    "fn": "DE",
    "n": "Network monitoring"
  },
  {
    "id": "DE.CM-02",
    "cat": "DE.CM",
    "fn": "DE",
    "n": "Physical environment monitoring"
  },
  {
    "id": "DE.CM-03",
    "cat": "DE.CM",
    "fn": "DE",
    "n": "Personnel and usage monitoring"
  },
  {
    "id": "DE.CM-06",
    "cat": "DE.CM",
    "fn": "DE",
    "n": "Supplier activity monitoring"
  },
  {
    "id": "DE.CM-09",
    "cat": "DE.CM",
    "fn": "DE",
    "n": "Computing environment monitoring"
  },
  {
    "id": "DE.AE-02",
    "cat": "DE.AE",
    "fn": "DE",
    "n": "Adverse events analyzed"
  },
  {
    "id": "DE.AE-03",
    "cat": "DE.AE",
    "fn": "DE",
    "n": "Information correlated"
  },
  {
    "id": "DE.AE-04",
    "cat": "DE.AE",
    "fn": "DE",
    "n": "Impact and scope understood"
  },
  {
    "id": "DE.AE-06",
    "cat": "DE.AE",
    "fn": "DE",
    "n": "Information provided to staff"
  },
  {
    "id": "DE.AE-07",
    "cat": "DE.AE",
    "fn": "DE",
    "n": "Threat intelligence integrated"
  },
  {
    "id": "DE.AE-08",
    "cat": "DE.AE",
    "fn": "DE",
    "n": "Incidents declared"
  },
  {
    "id": "RS.MA-01",
    "cat": "RS.MA",
    "fn": "RS",
    "n": "Response plan executed"
  },
  {
    "id": "RS.MA-02",
    "cat": "RS.MA",
    "fn": "RS",
    "n": "Reports triaged"
  },
  {
    "id": "RS.MA-03",
    "cat": "RS.MA",
    "fn": "RS",
    "n": "Incidents categorized"
  },
  {
    "id": "RS.MA-04",
    "cat": "RS.MA",
    "fn": "RS",
    "n": "Incidents escalated"
  },
  {
    "id": "RS.MA-05",
    "cat": "RS.MA",
    "fn": "RS",
    "n": "Recovery criteria applied"
  },
  {
    "id": "RS.AN-03",
    "cat": "RS.AN",
    "fn": "RS",
    "n": "Root cause analysis"
  },
  {
    "id": "RS.AN-06",
    "cat": "RS.AN",
    "fn": "RS",
    "n": "Investigation records preserved"
  },
  {
    "id": "RS.AN-07",
    "cat": "RS.AN",
    "fn": "RS",
    "n": "Incident data collected"
  },
  {
    "id": "RS.AN-08",
    "cat": "RS.AN",
    "fn": "RS",
    "n": "Incident magnitude estimated"
  },
  {
    "id": "RS.CO-02",
    "cat": "RS.CO",
    "fn": "RS",
    "n": "Stakeholders notified"
  },
  {
    "id": "RS.CO-03",
    "cat": "RS.CO",
    "fn": "RS",
    "n": "Information shared"
  },
  {
    "id": "RS.MI-01",
    "cat": "RS.MI",
    "fn": "RS",
    "n": "Incidents contained"
  },
  {
    "id": "RS.MI-02",
    "cat": "RS.MI",
    "fn": "RS",
    "n": "Incidents eradicated"
  },
  {
    "id": "RC.RP-01",
    "cat": "RC.RP",
    "fn": "RC",
    "n": "Recovery plan executed"
  },
  {
    "id": "RC.RP-02",
    "cat": "RC.RP",
    "fn": "RC",
    "n": "Recovery actions performed"
  },
  {
    "id": "RC.RP-03",
    "cat": "RC.RP",
    "fn": "RC",
    "n": "Backup integrity verified"
  },
  {
    "id": "RC.RP-04",
    "cat": "RC.RP",
    "fn": "RC",
    "n": "Post-incident norms established"
  },
  {
    "id": "RC.RP-05",
    "cat": "RC.RP",
    "fn": "RC",
    "n": "Assets restored and verified"
  },
  {
    "id": "RC.RP-06",
    "cat": "RC.RP",
    "fn": "RC",
    "n": "Recovery declared complete"
  },
  {
    "id": "RC.CO-03",
    "cat": "RC.CO",
    "fn": "RC",
    "n": "Recovery progress communicated"
  },
  {
    "id": "RC.CO-04",
    "cat": "RC.CO",
    "fn": "RC",
    "n": "Public recovery updates"
  }
];

const GV_CORE_SUBCATEGORIES = [
  "GV.PO-01",
  "GV.PO-02",
  "GV.RR-01",
  "GV.RR-02",
  "GV.RR-03",
  "GV.RM-01",
  "GV.RM-02",
  "GV.RM-06",
  "GV.OC-01",
  "GV.OV-01"
];

const CATEGORY_SUGGESTED_ROLES = {
  "GV.OC": "Program Leadership",
  "GV.RM": "GRC Lead",
  "GV.RR": "Program Leadership",
  "GV.PO": "GRC Lead",
  "GV.OV": "Program Leadership",
  "GV.SC": "Vendor Risk Lead",
  "ID.AM": "IT Operations Lead",
  "ID.RA": "GRC Lead",
  "ID.IM": "GRC Lead",
  "PR.AA": "IAM Lead",
  "PR.AT": "People Lead",
  "PR.DS": "Data Protection Lead",
  "PR.PS": "Security Engineering Lead",
  "PR.IR": "Infrastructure Lead",
  "DE.CM": "Security Operations Lead",
  "DE.AE": "Security Operations Lead",
  "RS.MA": "Incident Response Lead",
  "RS.AN": "Incident Response Lead",
  "RS.CO": "Communications Lead",
  "RS.MI": "Incident Response Lead",
  "RC.RP": "Business Continuity Lead",
  "RC.CO": "Communications Lead"
};

const FUNCTION_SUGGESTED_ROLES = {
  "GV": "Program Leadership",
  "ID": "GRC Lead",
  "PR": "Security Engineering Lead",
  "DE": "Security Operations Lead",
  "RS": "Incident Response Lead",
  "RC": "Business Continuity Lead"
};

const FUNCTION_DESC = {
  "GV": "The organization's cybersecurity risk management strategy, expectations, and policy are established, communicated, and monitored.",
  "ID": "The organization's current cybersecurity risks are understood.",
  "PR": "Safeguards to manage the organization's cybersecurity risks are used.",
  "DE": "Possible cybersecurity attacks and compromises are found and analyzed.",
  "RS": "Actions regarding a detected cybersecurity incident are taken.",
  "RC": "Assets and operations affected by a cybersecurity incident are restored."
};

const CATEGORY_DESC = {
  "GV.OC": "The circumstances — mission, stakeholder expectations, dependencies, and legal, regulatory, and contractual requirements — surrounding the organization's cybersecurity risk management decisions are understood.",
  "GV.RM": "The organization's priorities, constraints, risk tolerance and appetite statements, and assumptions are established, communicated, and used to support operational risk decisions.",
  "GV.RR": "Cybersecurity roles, responsibilities, and authorities to foster accountability, performance assessment, and continuous improvement are established and communicated.",
  "GV.PO": "Organizational cybersecurity policy is established, communicated, and enforced.",
  "GV.OV": "Results of organization-wide cybersecurity risk management activities and performance are used to inform, improve, and adjust the risk management strategy.",
  "GV.SC": "Cyber supply chain risk management processes are identified, established, managed, monitored, and improved by organizational stakeholders.",
  "ID.AM": "Assets (e.g., data, hardware, software, systems, facilities, services, people) that enable the organization to achieve business purposes are identified and managed consistent with their relative importance to organizational objectives and the organization's risk strategy.",
  "ID.RA": "The cybersecurity risk to the organization, assets, and individuals is understood by the organization.",
  "ID.IM": "Improvements to organizational cybersecurity risk management processes, procedures and activities are identified across all CSF Functions.",
  "PR.AA": "Access to physical and logical assets is limited to authorized users, services, and hardware and managed commensurate with the assessed risk of unauthorized access.",
  "PR.AT": "The organization's personnel are provided with cybersecurity awareness and training so that they can perform their cybersecurity-related tasks.",
  "PR.DS": "Data are managed consistent with the organization's risk strategy to protect the confidentiality, integrity, and availability of information.",
  "PR.PS": "The hardware, software (e.g., firmware, operating systems, applications), and services of physical and virtual platforms are managed consistent with the organization's risk strategy to protect their confidentiality, integrity, and availability.",
  "PR.IR": "Security architectures are managed with the organization's risk strategy to protect asset confidentiality, integrity, and availability, and organizational resilience.",
  "DE.CM": "Assets are monitored to find anomalies, indicators of compromise, and other potentially adverse events.",
  "DE.AE": "Anomalies, indicators of compromise, and other potentially adverse events are analyzed to characterize the events and detect cybersecurity incidents.",
  "RS.MA": "Responses to detected cybersecurity incidents are managed.",
  "RS.AN": "Investigations are conducted to ensure effective response and support forensics and recovery activities.",
  "RS.CO": "Response activities are coordinated with internal and external stakeholders as required by laws, regulations, or policies.",
  "RS.MI": "Activities are performed to prevent expansion of an event and mitigate its effects.",
  "RC.RP": "Restoration activities are performed to ensure operational availability of systems and services affected by cybersecurity incidents.",
  "RC.CO": "Restoration activities are coordinated with internal and external parties."
};

/** Preset category merges for CISO consolidate step (category policy mode only). */
const COMMON_CATEGORY_MERGES = [
  {
    "slaves": [
      "PR.AT"
    ],
    "master": "PR.AA",
    "label": "People & Access",
    "reason": "Awareness and training (PR.AT) supports access and identity practices (PR.AA) under one policy owner."
  },
  {
    "slaves": [
      "DE.AE"
    ],
    "master": "DE.CM",
    "label": "Detection Operations",
    "reason": "Continuous monitoring (DE.CM) and adverse-event analysis (DE.AE) are operated together."
  },
  {
    "slaves": [
      "RS.AN",
      "RS.CO",
      "RS.MI"
    ],
    "master": "RS.MA",
    "label": "Incident Response",
    "reason": "Response management, analysis, coordination, and mitigation are one operational workflow."
  },
  {
    "slaves": [
      "RC.CO"
    ],
    "master": "RC.RP",
    "label": "Recovery",
    "reason": "Restoration planning and recovery coordination belong under one recovery policy owner."
  },
  {
    "slaves": [
      "ID.IM"
    ],
    "master": "ID.RA",
    "label": "Risk Assessment & Continuous Improvement",
    "reason": "Risk assessment (ID.RA) and improvement activities (ID.IM) are owned together in lean programs."
  }
];

/** Legacy aliases — map old 800-53 helper names to CSF catalog during migration. */
const FAMILIES = FUNCTIONS;
const CONTROLS = SUBCATEGORIES.map(function(s) {
  return { id: s.id, f: s.fn, cat: s.cat, n: s.n };
});

const DOMAIN_SUGGESTED_ROLES = CATEGORY_SUGGESTED_ROLES;

function getCategoryById(catId) {
  for (var i = 0; i < CATEGORIES.length; i++) {
    if (CATEGORIES[i].id === catId) return CATEGORIES[i];
  }
  return null;
}

function getSubcategoryById(subId) {
  for (var i = 0; i < SUBCATEGORIES.length; i++) {
    if (SUBCATEGORIES[i].id === subId) return SUBCATEGORIES[i];
  }
  return null;
}

function getCategoriesForFunction(fn) {
  return CATEGORIES.filter(function(c) { return c.fn === fn; });
}

function getSubcategoriesForCategory(catId) {
  return SUBCATEGORIES.filter(function(s) { return s.cat === catId; });
}

function getDefaultSelectedCategories() {
  var out = {};
  CATEGORIES.forEach(function(c) { out[c.id] = true; });
  return out;
}

function getDefaultGvSubcategories() {
  var out = {};
  GV_CORE_SUBCATEGORIES.forEach(function(id) { out[id] = true; });
  SUBCATEGORIES.filter(function(s) { return s.fn === 'GV'; }).forEach(function(s) {
    out[s.id] = true;
  });
  return out;
}
